version: '3.0'
services:
  rasa:
    build:     
      dockerfile: Dockerfile
      context: ./rasabot
    ports:
      - 5005:5005
    volumes:
      - ./:/app
  webapp:
    build:     
      dockerfile: Dockerfile
      context: ./webapp
    ports:
      - 5000:5000
    